### ISSUE TITLE
Can only create spans if in TRACING mode

### ISSUE THREAD

**Issue by david-garcia-garcia** [tideways/profiler#5]
```
    public static function createSpan($name)
    {
        return (self::$mode & self::MODE_TRACING) > 0
            ? self::$currentRootSpan->createSpan($name)
            : new \Tideways\Traces\NullSpan();
    }
```

Not sure why, but looks like custom spans are only supported in tracing mode?

I'm working on the Drupal 8 integration:

https://www.drupal.org/project/tideways

In symfony 2 - for example - code can run after the response has been sent to the user (after the kernel terminate event). It is important to separate the real kernel span from the global request itself (or default "app span" created by Tideways).

**Comment by beberlei** [comment]
@david-garcia-garcia that is correct, in monitoring mode custom spans are just ignored. That is no problem, because tracing mode is whenever a timeline is generated. Since we return a NullSpan, your client side code will still work as well, no need to handle this yourself.
